### ISSUE TITLE
Theme without Google Fonts

### ISSUE THREAD

**Issue by git-dimiz** [mrpbennett/catppucin-homer#2]
Hi

I really appreciate the themes!!! The only remark I have is that the CSS imports Google Fonts. Is it possible to provide instructions to not use Google Fonts or to download them locally?

**Comment by mrpbennett** [comment]
Sure you can fork your own version of this, remove the line importing the fonts and you can simply download them and install them on your local machine.  You can download the font from here

https://fonts.google.com/specimen/Fira+Code
